"""Turn greeting words into SVG path data using the OFL font Sacramento,
so the extension can draw them (no font needs to be installed)."""
import json
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.boundsPen import BoundsPen

font = TTFont('Sacramento.ttf')
glyphs = font.getGlyphSet()
cmap = font.getBestCmap()
upem = font['head'].unitsPerEm
k = 1000.0 / upem

WORDS = [
    ('en', 'hello'), ('fr', 'bonjour'), ('es', 'hola'), ('de', 'hallo'),
    ('it', 'ciao'), ('pt', 'olá'), ('sv', 'hej'), ('fr2', 'salut'),
]

out = {}
for lang, word in WORDS:
    pen = SVGPathPen(glyphs, ntos=lambda v: ('%.1f' % v).rstrip('0').rstrip('.'))
    bounds = BoundsPen(glyphs)
    x = 0
    for ch in word:
        name = cmap[ord(ch)]
        # y is flipped (SVG), scaled to a 1000-unit em; origin at the baseline.
        transform = (k, 0, 0, -k, x * k, 0)
        glyphs[name].draw(TransformPen(pen, transform))
        glyphs[name].draw(TransformPen(bounds, transform))
        x += glyphs[name].width
    x0, y0, x1, y1 = bounds.bounds
    out[lang] = {'text': word, 'd': pen.getCommands(), 'box': [round(x0, 1), round(y0, 1), round(x1, 1), round(y1, 1)]}

js = '''// Greeting words as vector paths (1000-unit em, y down, baseline at 0), made
// from the Sacramento font by Astigmatic, SIL Open Font License 1.1
// (https://scripts.sil.org/OFL). Generated by tools/make_hello.py: do not edit.

export const HELLO_WORDS = %s;
''' % json.dumps(out, ensure_ascii=False, indent=2)
open('helloPaths.js', 'w', encoding='utf-8').write(js)
for lang, w in out.items():
    print(lang, w['text'], w['box'], len(w['d']))
